name: EdcariaTournamentPlugin
version: 1.0
author: JupiterPi
main: de.jupiterpi.mc.edcaria.EdcariaTournamentPlugin
api-version: 1.17
commands:
  tournament:
    description: Tournament-related commands
    usage: /tournament <create|start>
  tournament-config:
    description: Tournament configuration
    usage: /tournament-config <attribute> [<value>]
  ec:
    description: Opens your enderchest.
    usage: /ec